### ISSUE TITLE
EditTableCommands is not exported from slate-editable-table

### ISSUE THREAD

**Issue by vamshi9** [bokuweb/slate-editable-table#26]
I am trying to implement this awesome table over an application where it is a `jsx` file. I am not finding 2 issues in importing the package. 
1) Not sure how I can do this in react `editor!: Editor & EditTableCommands;` and can you explain what this is doing?
2) I am facing the issue `EditTableCommands is not exported from slate-editable-table`.

Thank you for this awesome project! @bokuweb

**Comment by vamshi9** [comment]
Okay, I have come up with the `codesandbox`. it seems like the second issue is resolved but still, EditTableCommand is not getting utilized. Could you please take a look into this!

**Comment by bokuweb** [comment]
@vamshi9 A following link is fixed example.

https://codesandbox.io/s/slate-editable-table-lel8q

> Not sure how I can do this in react editor!: Editor & EditTableCommands; and can you explain what this is doing?

It is type definition for typescript. If you don't use typescript , it is not needed.

> I am facing the issue EditTableCommands is not exported from slate-editable-table

It is same reason above.

**Comment by vamshi9** [comment]
Awesome! I am trying to understand your approaches over the libs you have written. I would love to contribute to this project. This is the best tables ever! Thanks once again for this awesome awesome project @bokuweb
