### ISSUE TITLE
[Slate]Do you have the plan to upgrade the deps of Slate to the latest version?

### ISSUE THREAD

**Issue by lqs469** [bokuweb/slate-editable-table#37]
Hello!
First of all, This repo is the most powerful table plugins of slate.js, It's awesome! 👍Thanks for your wonderful work!👍

And you know, After Slate releasing this version from May 2019 PR. They changed a lot of APIs and it causes a lot of plugins that did not work anymore, slate-editable-table is one of those.😫

So, I want to know that do you have the plan to develop a new version to match the new Slate.js APIs? You know, basically it will refactor most of the project.🤯

**Comment by bokuweb** [comment]
@lqs469 Thanks for your message :+1: 

> And you know, After Slate releasing this version from May 2019 PR. They changed a lot of APIs and it causes a lot of plugins that did not work anymore, slate-editable-table is one of those.tired_face

I know :sob: 

> So, I want to know that do you have the plan to develop a new version to match the new Slate.js APIs? You know, basically it will refactor most of the project.🤯

So, there is a huge change in slatejs 0.5 and I guess  this plugin can not follow it. I think if we support slatejs v0.5 we need to rewrite entire code. So I have no plan to do it for now. sorry...

**Comment by lqs469** [comment]
Ok, Got you. Anyway thank you again~ 😃
Maybe I can do something for it, Do you mind fork your repo? You know, it can't forward compatibility, So maybe I will start a new repo to refactor the entire code?

**Comment by bokuweb** [comment]
@lqs469 

> Maybe I can do something for it, Do you mind fork your repo? You know, it can't forward compatibility, So maybe I will start a new repo to refactor the entire code?

Welcome!!Feel free to use my code :smile:

**Comment by lqs469** [comment]
@bokuweb 
> Welcome!!Feel free to use my code 😄

Thx~ So I think you can close this issue.😄
